language: generic 

sudo: required
services:
  -docker

before_install:
  - docker build -t jdbanerjee-godam/docker-react -f Dockerfile.dev .

script:
  - docker run jdbanerjee-godam/docker-react npm run test -- --coverage